sudo: required
dist: trusty
language: cpp

cache:
  directories:
    /tmp/gflags-2.1.2
    /tmp/glog-0.3.4
    /tmp/grpc

env:
  - CXX=g++-4.7 CC=gcc-4.7
  - CXX=g++-5 CC=gcc-5

before_install:
  - sudo sysctl -w vm.nr_hugepages=1024
  - sudo mkdir -p /mnt/huge
  - sudo mount -t hugetlbfs nodev /mnt/huge

install:
  - sudo add-apt-repository -y 'deb http://us.archive.ubuntu.com/ubuntu yakkety main universe'
  - sudo apt-get update
  - sudo apt-get install -y g++-4.7
  - sudo apt-get install -y -t yakkety g++-5
  - sudo apt-get install -y cmake
  - sudo apt-get install -y autoconf automake libtool make unzip
  - sudo apt-get install -y python python-scapy libpcap-dev
  - sudo apt-get install -y libgraph-easy-perl linux-headers-$(uname -r)
  - sudo apt-get install -y -t yakkety libgtest-dev
  - sudo apt-get install -y -t yakkety libgflags-dev
  - sudo apt-get install -y -t yakkety libgoogle-glog0v5
  - sudo apt-get install -y -t yakkety libgoogle-glog-dev
  - sudo apt-get install -y -t yakkety protobuf-compiler
  - sudo apt-get install -y -t yakkety libprotoc-dev
  - sudo apt-get install -y -t yakkety libgrpc0
  - sudo apt-get install -y -t yakkety libgrpc-dev
  - .travis/install-grpc.sh

script:
  - grpc_cpp_plugin asas
  - ./build.py
  - sudo bin/bessd -g

notifications:
  slack: nefeli:x5udJ7nDIKjCaCrRYprGc4mw
